codecov:
  token: d5c9d182-dd12-4d88-bb82-bca741f03010

codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    round: nearest
    precision: 2
    status:
        project:
            default:
                target: 50%
        patch:
            default:
                target: 50%
        changes: yes

comment:
    require_changes: yes
