language: python
dist: xenial

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
  allow_failures:	
    - python: 3.9-dev

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements_dev.txt

install:
  - python setup.py sdist bdist_wheel

script:
  - pytest

after_success:
  - codecov

notifications:
  email:
    recipients:
      - achokshi@student.unimelb.edu.au
    on_success: change
    on_failure: always
