language: python
dist: xenial

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8
    - python: 3.8-dev
    - python: 3.9-dev
  allow_failures:
    - python: 3.9-dev

before_install:
  - pip install -U pip
  - python -m pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - pip install -U pytest

install:
  - pip install .

script:
  - pytest


notifications:
  email:
    recipients:
      - achokshi@student.unimelb.edu.au
    on_success: change
    on_failure: always
