"""
Chronological Ephemeris
-----------------------

Collate ephemeris data generated by :mod:`~embers.sat_utils.sat_ephemeris` for multiple satellites
and determine all ephemeris present in 30 minute observation windows.

"""

import os
import json
import math
from datetime import datetime, timedelta
from pathlib import Path
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor

import numpy as np
import pytz
from scipy import interpolate

from __future__ import annotations


def obs_times(time_zone, start_date, stop_date):
    """Time conversion tools for 30 minute observations

    Given a :samp:`time_zone`, :samp:`start_date`, :samp:`stop_date`,
    create lists of human readable start times in :samp:`YYYY-MM-DD-HH:MM`
    format, and start and stop UNIX times for 30 minute rf observations.

    .. code-block:: python

        from embers.sat_utils.chrono_ephem import obs_times
        time_tuple = obs_times("Australia/Perth", "2020-01-01", "2020-01-02")
        obs_time, obs_unix, obs_unix_end - time_tuple

        print(obs_time)
        >>> ["2020-01-01-00:00", "2020-01-01-00:30", ....]

        print(obs_unix)
        >>> [1577809800.0, 1577811600.0, 1577813400.0, ...]

        print(obs_unix_end)
        >>> [1577809800.0, 1577811600.0, 1577813400.0, ...]

    :param time_zone: A :class:`~str` representing a :samp:`pytz` `timezones <https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568>`_.
    :param start_date: in :samp:`YYYY-MM-DD` format :class:`~str`
    :param stop_date: in :samp:`YYYY-MM-DD` format :class:`~str`

    :returns:
        A :class:`~tuple` (obs_time, obs_unix, obs_unix_end)

        - obs_time: :class:`~list` of start times of 30 min observations in :samp:`YYYY-MM-DD-HH::MM` format
        - obs_unix: :class:`~list` of start times of 30 min observations in unix time
        - obs_unix_end: :class:`~list` of end times of 30 min observations in unix time

    """

    # Time stuff
    # The time input is in local time. As in Austraila/Perth
    local = pytz.timezone(time_zone)

    t_start = datetime.strptime(start_date, "%Y-%m-%d")
    t_stop = datetime.strptime(stop_date, "%Y-%m-%d")

    # Number of days that the date range spans
    n_days = (t_stop - t_start).days

    # YYYY-MM-DD-HH:MM format
    obs_time = []

    # Start of half hour obs in unix time
    obs_unix = []

    # End of half hour obs in unix time
    obs_unix_end = []

    # The +1 makes the date ranges inclusive
    for i in range(n_days + 1):
        day = t_start + timedelta(days=i)
        date = day.strftime("%Y-%m-%d")

        # loop over 48x30 minute obs in a day
        for j in range(48):
            t_delta = datetime.strptime(date, "%Y-%m-%d") + timedelta(minutes=30 * j)
            # convert t_delta to a readable string YYYY-MM-DD-HH:MM
            d_time = t_delta.strftime("%Y-%m-%d-%H:%M")

            # Convert from naive local time to utc aware time
            utc_delta = local.localize(t_delta, is_dst=None).astimezone(pytz.utc)

            # convert to a unix timestamp, used within rf explorer data files
            utc_unix = utc_delta.timestamp()
            # time at end of half hour window
            utc_unix_end = utc_unix + (30 * 60)

            obs_time.append(d_time)
            obs_unix.append(utc_unix)
            obs_unix_end.append(utc_unix_end)

    return (obs_time, obs_unix, obs_unix_end)


def interp_ephem(t_array, s_alt, s_az, interp_type, interp_freq):
    """Interpolates satellite ephemeris from :mod:`~embers.sat_utils.sat_ephemeris`

    Satellite ephemeris is interpolated to the same freq as used in :mod:`~embers.rf_tools.align_data`.
    This ensures that each point of rf data, will have an corresponding ephemeris.
    :samp:`Time`, :samp:`Altitude` & :samp:`Azimuth` ephemeris arrays are interpolated.

    :param t_array: Time array of on satellite pass :class:`~numpy.ndarray`
    :param s_alt: Satellite :samp:`Altitude` at the :samp:`t_array` :class:`~numpy.ndarray`
    :param s_az: Satellite :samp:`Azimuth` at the :samp:`t_array` :class:`~numpy.ndarray`
    :param interp_type: Type of interpolation. Ex: :samp:`cubic`, :samp:`linear` :class:`str`
    :param interp_freq: Frequency at which to interpolate, in Hertz. :class:`~int`

    :returns:
        A :class:`~tuple` (time_interp, sat_alt, sat_az)

        - time_interp: Interpolated :samp:`t_array`
        - sat_alt: Interpolated :samp:`s_alt`
        - sat_az: Interpolated :samp:`s_az`

    """

    # Create interpolation functions. Math functions, not Python!
    alt_interp = interpolate.interp1d(t_array, s_alt, kind=interp_type)

    # The next step was a bit tricky. Azimuth may wrap around.
    # This may lead to a discontinuity between 0, 2π
    # We deal with this, by unwrapping the angles

    # This extends the angles beyond 2π, if the angles cross the discontinuity
    s_az_cont = np.unwrap(s_az)
    az_interp = interpolate.interp1d(t_array, s_az_cont, kind=interp_type)

    # Makes start and end times clean integers
    # Also ensures that the interp range is inclusive of data points
    start = math.ceil(t_array[0])
    stop = math.floor(t_array[-1])

    # Create time array, at which to evaluate alt/az of sat
    time_interp = list(np.double(np.arange(start, stop, (1 / interp_freq))))

    sat_alt = list(alt_interp(time_interp))

    # The modulus division by 2π, un-does the np.unwrap
    sat_az = list(az_interp(time_interp) % (2 * np.pi))

    return (time_interp, sat_alt, sat_az)


def write_json(data, filename=None, out_dir=None):
    """writes data to json file in output dir

    :param data: Data to be written to json file
    :param filename: Json filename :class:`~str`
    :param out_dir: Path to output directory :class:`~str`

    """

    with open(f"{out_dir}/{filename}", "w") as f:
        json.dump(data, f, indent=4)


# def save_chrono_ephem(
#     time_zone, start_date, stop_date, interp_type, interp_freq, ephem_dir, out_dir
# ):
#     """Save 30 minute ephem from all satellites to file.
#
#     Native skyfiled gps timestamps are converted to unix
#     timestamps to match the output of the rf explorers. The
#     alt, az data is interpolated to match the cadence of
#     :mod:`~embers.rf_tools.align_data`. Make a json file with all the passes
#     from each 30 min observation. This will help in the
#     next stage, where we identify all sats in each obs.
#
#     :param time_zone: A :class:`~str` representing a :samp:`pytz` `timezones <https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568>`_.
#     :param start_date: in :samp:`YYYY-MM-DD` format :class:`~str`
#     :param stop_date: in :samp:`YYYY-MM-DD` format :class:`~str`
#     :param interp_type: Type of interpolation. Ex: :samp:`cubic`, :samp:`linear` :class:`str`
#     :param interp_freq: Frequency at which to interpolate, in Hertz. :class:`~int`
#     :param ephem_dir: Directory where :samp:`npz` ephemeris files from :func:`~embers.sat_utils.sat_ephemeris.save_ephem` are saved :class:`~str`
#     :param out_dir: Path to output directory where chronological ephemeris files will be saved :class:`~str`
#
#     """
#
#     obs_time, obs_unix, obs_unix_end = obs_times(time_zone, start_date, stop_date)
#
#     # creates output dir, if it doesn't exist
#     Path(out_dir).mkdir(parents=True, exist_ok=True)
#
#     # Lets make the a json file for each 30 min observation, with an empty list
#     data = []
#     for i in range(len(obs_time)):
#         write_json(data, filename=f"{obs_time[i]}.json", out_dir=out_dir)
#
#     # Finds all sat ephem json files, and loops over them
#     for ephem_npz in list(Path(ephem_dir).glob("*.npz")):
#
#         # Extract data from npz ephem file
#         sat_ephem = np.load(ephem_npz, allow_pickle=True)
#         t_array = sat_ephem["time_array"]
#         s_alt = sat_ephem["sat_alt"]
#         s_az = sat_ephem["sat_az"]
#         s_id = str(sat_ephem["sat_id"])
#
#         # here, we're looping over each satellite pass with a single sat ephem file
#         # to check which observation window it falls in
#         for pass_idx in range(len(t_array)):
#
#             # if sat ephem has more than 10 data points
#             if t_array[pass_idx].shape[0] >= 10:
#
#                 time_interp, sat_alt, sat_az = interp_ephem(
#                     t_array[pass_idx],
#                     s_alt[pass_idx],
#                     s_az[pass_idx],
#                     interp_type,
#                     interp_freq,
#                 )
#
#                 # Find which sat passes are within a 30 minute obs
#                 for obs_int in range(len(obs_unix)):
#
#                     sat_ephem = {}
#                     sat_ephem["sat_id"] = [s_id]
#                     sat_ephem["time_array"] = []
#                     sat_ephem["sat_alt"] = []
#                     sat_ephem["sat_az"] = []
#
#                     # Case I: Satpass occurs completely within the 30min observation
#                     if (
#                         obs_unix[obs_int] < time_interp[0]
#                         and obs_unix_end[obs_int] > time_interp[-1]
#                     ):
#
#                         # append the whole pass to the dict
#                         sat_ephem["time_array"].extend(time_interp)
#                         sat_ephem["sat_alt"].extend(sat_alt)
#                         sat_ephem["sat_az"].extend(sat_az)
#
#                     # Case II: Satpass begins before the obs, but ends within it
#                     elif (
#                         obs_unix[obs_int] > time_interp[0]
#                         and obs_unix[obs_int] < time_interp[-1]
#                         and obs_unix_end[obs_int] > time_interp[-1]
#                     ):
#
#                         # find index of time_interp == obs_unix
#                         start_idx = (
#                             np.where(np.asarray(time_interp) == obs_unix[obs_int])
#                         )[0][0]
#
#                         # append the end of the pass which is within the obs
#                         sat_ephem["time_array"].extend(time_interp[start_idx:])
#                         sat_ephem["sat_alt"].extend(sat_alt[start_idx:])
#                         sat_ephem["sat_az"].extend(sat_az[start_idx:])
#
#                     # Case III: Satpass begins within the obs, but ends after it
#                     elif (
#                         obs_unix_end[obs_int] > time_interp[0]
#                         and obs_unix_end[obs_int] < time_interp[-1]
#                         and obs_unix[obs_int] < time_interp[0]
#                     ):
#
#                         # find index of time_interp == obs_unix_end
#                         stop_idx = (
#                             np.where(np.asarray(time_interp) == obs_unix_end[obs_int])
#                         )[0][0]
#
#                         # append the end of the pass which is within the obs
#                         sat_ephem["time_array"].extend(time_interp[: stop_idx + 1])
#                         sat_ephem["sat_alt"].extend(sat_alt[: stop_idx + 1])
#                         sat_ephem["sat_az"].extend(sat_az[: stop_idx + 1])
#
#                     # doesn't create json if there are no satellite passes within it
#                     if sat_ephem["time_array"] != []:
#
#                         print(f"Satellite {s_id} in {obs_time[obs_int]}")
#
#                         # open the relevant json file and loads contents to 'data_json'
#                         with open(f"{out_dir}/{obs_time[obs_int]}.json") as json_file:
#                             data_json = json.load(json_file)
#
#                             # append new satpass ephem data to data_json
#                             data_json.append(sat_ephem)
#
#                             # write the combined data back to the original file
#                             write_json(
#                                 data_json,
#                                 filename=f"{obs_time[obs_int]}.json",
#                                 out_dir=out_dir,
#                             )
#
#                             # clear data_json
#                             data_json = []


# def save_chrono_ephem(
#     time_zone,
#     start_date,
#     stop_date,
#     interp_type,
#     interp_freq,
#     ephem_dir,
#     out_dir,
# ):
#     """Save 30-minute chronological satellite ephemerides to JSON files.
#
#     Native Skyfield timestamps are converted to Unix timestamps to match the
#     RF Explorer timestamps. Satellite altitude and azimuth are interpolated
#     to the cadence used by :mod:`~embers.rf_tools.align_data`.
#
#     A JSON file is created for each 30-minute observation. Each file contains
#     the portions of all satellite passes that overlap that observation.
#
#     Parameters
#     ----------
#     time_zone
#         ``pytz`` timezone name.
#     start_date
#         Start date in ``YYYY-MM-DD`` format.
#     stop_date
#         Stop date in ``YYYY-MM-DD`` format.
#     interp_type
#         Interpolation type, for example ``"cubic"`` or ``"linear"``.
#     interp_freq
#         Interpolation frequency in Hz.
#     ephem_dir
#         Directory containing the satellite ephemeris ``npz`` files produced
#         by :func:`~embers.sat_utils.sat_ephemeris.save_ephem`.
#     out_dir
#         Directory in which the chronological ephemeris JSON files are saved.
#     """
#     obs_time, obs_unix, obs_unix_end = obs_times(
#         time_zone,
#         start_date,
#         stop_date,
#     )
#
#     out_path = Path(out_dir)
#     out_path.mkdir(parents=True, exist_ok=True)
#
#     # Create an empty JSON file for each 30-minute observation.
#     for observation in obs_time:
#         write_json(
#             [],
#             filename=f"{observation}.json",
#             out_dir=out_dir,
#         )
#
#     # Loop over all satellite ephemeris files.
#     for ephem_npz in Path(ephem_dir).glob("*.npz"):
#
#         # Extract data from the satellite ephemeris file.
#         with np.load(ephem_npz, allow_pickle=True) as ephem_data:
#             t_array = ephem_data["time_array"]
#             s_alt = ephem_data["sat_alt"]
#             s_az = ephem_data["sat_az"]
#             s_id = str(ephem_data["sat_id"])
#
#         # Loop over each pass contained in the ephemeris file.
#         for pass_idx in range(len(t_array)):
#
#             # Ignore passes containing fewer than 10 native samples.
#             if t_array[pass_idx].shape[0] < 10:
#                 continue
#
#             time_interp, sat_alt, sat_az = interp_ephem(
#                 t_array[pass_idx],
#                 s_alt[pass_idx],
#                 s_az[pass_idx],
#                 interp_type,
#                 interp_freq,
#             )
#
#             # Convert to arrays so searchsorted and slicing behave consistently.
#             time_interp = np.asarray(time_interp)
#             sat_alt = np.asarray(sat_alt)
#             sat_az = np.asarray(sat_az)
#
#             # Loop over each 30-minute observation window.
#             for obs_int in range(len(obs_unix)):
#                 obs_start = obs_unix[obs_int]
#                 obs_stop = obs_unix_end[obs_int]
#
#                 # Locate the portion of the pass inside the observation.
#                 #
#                 # side="left" includes samples exactly at obs_start.
#                 # side="right" includes samples exactly at obs_stop.
#                 start_idx = np.searchsorted(
#                     time_interp,
#                     obs_start,
#                     side="left",
#                 )
#                 stop_idx = np.searchsorted(
#                     time_interp,
#                     obs_stop,
#                     side="right",
#                 )
#
#                 # No satellite samples overlap this observation.
#                 if start_idx >= stop_idx:
#                     continue
#
#                 sat_ephem = {
#                     "sat_id": [s_id],
#                     "time_array": time_interp[start_idx:stop_idx].tolist(),
#                     "sat_alt": sat_alt[start_idx:stop_idx].tolist(),
#                     "sat_az": sat_az[start_idx:stop_idx].tolist(),
#                 }
#
#                 print(f"Satellite {s_id} in {obs_time[obs_int]}")
#
#                 json_path = out_path / f"{obs_time[obs_int]}.json"
#
#                 # Load the passes already associated with this observation.
#                 with json_path.open("r") as json_file:
#                     data_json = json.load(json_file)
#
#                 # Add this pass and write the updated list back to disk.
#                 data_json.append(sat_ephem)
#
#                 write_json(
#                     data_json,
#                     filename=json_path.name,
#                     out_dir=out_dir,
#                 )


def _process_ephem_file(
    ephem_npz,
    obs_time,
    obs_unix,
    obs_unix_end,
    interp_type,
    interp_freq,
):
    """Process one satellite ephemeris file.

    This helper must be defined at module scope so it can be used by
    ProcessPoolExecutor.

    Returns
    -------
    dict
        Mapping from observation index to satellite-pass dictionaries.
    """
    obs_unix = np.asarray(obs_unix, dtype=float)
    obs_unix_end = np.asarray(obs_unix_end, dtype=float)

    result = defaultdict(list)

    with np.load(ephem_npz, allow_pickle=True) as ephem_data:
        t_array = ephem_data["time_array"]
        s_alt = ephem_data["sat_alt"]
        s_az = ephem_data["sat_az"]
        s_id = str(ephem_data["sat_id"])

    for pass_idx in range(len(t_array)):
        pass_time = np.asarray(t_array[pass_idx])

        if pass_time.size < 10:
            continue

        time_interp, sat_alt, sat_az = interp_ephem(
            pass_time,
            s_alt[pass_idx],
            s_az[pass_idx],
            interp_type,
            interp_freq,
        )

        time_interp = np.asarray(time_interp)
        sat_alt = np.asarray(sat_alt)
        sat_az = np.asarray(sat_az)

        if time_interp.size == 0:
            continue

        pass_start = time_interp[0]
        pass_stop = time_interp[-1]

        # Find only the observation windows that could overlap this pass.
        #
        # first_obs:
        #     First observation whose end is at or after pass_start.
        #
        # last_obs:
        #     One past the final observation whose start is at or before
        #     pass_stop.
        first_obs = np.searchsorted(
            obs_unix_end,
            pass_start,
            side="left",
        )
        last_obs = np.searchsorted(
            obs_unix,
            pass_stop,
            side="right",
        )

        for obs_int in range(first_obs, last_obs):
            obs_start = obs_unix[obs_int]
            obs_stop = obs_unix_end[obs_int]

            start_idx = np.searchsorted(
                time_interp,
                obs_start,
                side="left",
            )
            stop_idx = np.searchsorted(
                time_interp,
                obs_stop,
                side="right",
            )

            if start_idx >= stop_idx:
                continue

            result[obs_int].append(
                {
                    "sat_id": [s_id],
                    "time_array": (
                        time_interp[start_idx:stop_idx].tolist()
                    ),
                    "sat_alt": (
                        sat_alt[start_idx:stop_idx].tolist()
                    ),
                    "sat_az": (
                        sat_az[start_idx:stop_idx].tolist()
                    ),
                }
            )

    return dict(result)


def save_chrono_ephem(
    time_zone,
    start_date,
    stop_date,
    interp_type,
    interp_freq,
    ephem_dir,
    out_dir,
):
    """Save 30-minute chronological satellite ephemerides to JSON files.

    Native Skyfield timestamps are converted to Unix timestamps to match the
    RF Explorer timestamps. Satellite altitude and azimuth are interpolated
    to the cadence used by :mod:`~embers.rf_tools.align_data`.

    Satellite ephemeris files are processed in parallel. JSON files are
    written only by the parent process to avoid concurrent-write conflicts.

    Parameters
    ----------
    time_zone
        ``pytz`` timezone name.
    start_date
        Start date in ``YYYY-MM-DD`` format.
    stop_date
        Stop date in ``YYYY-MM-DD`` format.
    interp_type
        Interpolation type, for example ``"cubic"`` or ``"linear"``.
    interp_freq
        Interpolation frequency in Hz.
    ephem_dir
        Directory containing satellite ephemeris ``npz`` files.
    out_dir
        Output directory for chronological ephemeris JSON files.
    """
    obs_time, obs_unix, obs_unix_end = obs_times(
        time_zone,
        start_date,
        stop_date,
    )

    obs_time = list(obs_time)
    obs_unix = np.asarray(obs_unix, dtype=float)
    obs_unix_end = np.asarray(obs_unix_end, dtype=float)

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    ephem_files = sorted(Path(ephem_dir).glob("*.npz"))

    max_workers=None,
    if max_workers is None:
        max_workers = int(
            os.environ.get(
                "SLURM_CPUS_PER_TASK",
                os.cpu_count() or 1,
            )
        )

    # Avoid starting more processes than there are files.
    max_workers = max(
        1,
        min(max_workers, len(ephem_files)),
    )

    # Accumulate all passes by observation. This keeps all JSON writing in
    # the parent process and avoids race conditions.
    observation_data = [
        [] for _ in obs_time
    ]

    worker_args = [
        (
            ephem_file,
            obs_time,
            obs_unix,
            obs_unix_end,
            interp_type,
            interp_freq,
        )
        for ephem_file in ephem_files
    ]

    if max_workers == 1:
        results = map(
            lambda args: _process_ephem_file(*args),
            worker_args,
        )
    else:
        with ProcessPoolExecutor(
            max_workers=max_workers
        ) as executor:
            results = executor.map(
                _process_ephem_file_from_args,
                worker_args,
            )

            # Consume results before leaving the executor context.
            results = list(results)

    for file_result in results:
        for obs_int, satellite_passes in file_result.items():
            observation_data[obs_int].extend(satellite_passes)

            for sat_pass in satellite_passes:
                print(
                    f"Satellite {sat_pass['sat_id'][0]} "
                    f"in {obs_time[obs_int]}"
                )

    # Write each observation file once, rather than repeatedly reading and
    # rewriting it for every overlapping satellite pass.
    for obs_int, observation in enumerate(obs_time):
        write_json(
            observation_data[obs_int],
            filename=f"{observation}.json",
            out_dir=out_dir,
        )
